* Third Party API
** BlockChain Wallet API
*** My Note
From the API description, it seems like a Wallet can be created. And the response will be a Wallet ID, an address for sending and receiving funds and a label attached to that address.
*** API Link
 https://blockchain.info/api/blockchain_wallet_api
 Need a running website to request an API key.
*** Create Wallet API
Create blockchain wallet programmatically!
*URL*: http://localhost:3000/api/v2/create
*Method*: POST or GET

- $password The password for the new wallet. Must be at least 10 characters in length.
- $api_code An API code with create wallets permission.
- $priv A private key to add to the wallet (Wallet import format preferred). (Optional)
- $label A label to set for the first address in the wallet. Alphanumeric only. (Optional)
- $email An email to associate with the new wallet i.e. the email address of the user you are creating this wallet on behalf of. (Optional)
Please create an API code here including permissions to "Create Wallets".

Response will be like:
#+BEGIN_SRC json
{
    "guid": "4b8cd8e9-9480-44cc-b7f2-527e98ee3287",
    "address": "12AaMuRnzw6vW6s2KPRAGeX53meTf8JbZS",
    "label": "Main address"
}
#+END_SRC
*** Receive Payments API v2
[[https://blockchain.info/api/api_receive][Blockchain Payments API]]



** SpectroCoin Bitcoin API

* Bitcoin Wallet
* ETH
** 发行数字代币
** 一键发布平台(是否可靠)
** 智能合约
