* Multilevel Marketing
** Is it Legal?
[[https://www.economist.com/business/2013/01/05/the-bottom-line][The Bottom Line]]
[[http://www.kellogg.northwestern.edu/faculty/coughlan/htm/PersonalPage_Files/Papers/Assessing%20an%20MLM%20Business%20HLF%20as%20a%20Legit%20MLM%207-30-2012%20FINAL.pdf][Herbalife as a Legitimate MLM]]

* Variation of Plans
[[https://infinitemlmsoftware.com/mlm-plans.php][MLM Plans]]

** Binary MLM Plan

** Matrix MLM Plan
Fixed Width, encouraging hire more members in the downline.

** Unilevel
Unlimited width

** Generation Plan
 if you pay 10% of your very first generation, it will only be 6% on the second, 4% on the third generation, and 2% on the fourth.

** Monoline MLM Plan
Every member automatically goes down once new member join. 

** MLM Spillover
MLM spillover consists of the fact that a person in the upline decides to place a recruited person in the downline.

Profit grows as the downline person performs the operations. Spillover means a person spills over to the person in the downline. When we choose to place our new downline under a person in our team it would be an effective downline retention move that we can use

** Final Choice
Limit Width? or Height?




* My Question
If we are going to pay the transaction fee back, what should we use to reward new recruiment?

- Kucoin use part of users' transaction fee to pay their upliners.
- 


* FCOIN API
api.key:

71552b312b8f4217943e81a4de840f46

api.secret:

0570c98d38c4466ea4219d477a579f7c


* Tomorrow
** Model
Cryptocurrencies are mainly platforms/utilities built with an agenda of Generating value and assigning that value to a token to have transparency within the economy.
*** 


** Robot


** 180%

* 交易即挖矿
本质: 鼓励交易、提升自发代币的持有量

* FCOIN Automatic Program
[[https://github.com/DeepAiLearner/fcoin_python_sdk.git][FCOIN_python_sdk]]

* OKEx

** 投票上币



